---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  chef_license: accept-no-persist
  product_name: chef
  product_version: 18
  install_strategy: always
  multiple_converge: 2
  enforce_idempotency: true
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-24.04
    driver:
      box: bento/ubuntu-24.04
  - name: ubuntu-22.04
    driver:
      box: bento/ubuntu-22.04
  - name: debian-12
    driver:
      box: bento/debian-12
  - name: rockylinux-9
    driver:
      box: bento/rockylinux-9
  - name: amazonlinux-2023
    driver:
      box: bento/amazonlinux-2023

suites:
  - name: default
    run_list:
      - recipe[cookbook-template::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      cookbook_template:
        service:
          port: 8080
          enabled: true