---
driver:
  name: dokken
  privileged: true
  chef_image: chef/chef
  chef_version: 19

provisioner:
  name: dokken
  chef_license: accept-no-persist
  product_name: chef
  install_strategy: always
  multiple_converge: 2
  enforce_idempotency: true
  deprecations_as_errors: true

verifier:
  name: inspec

transport:
  name: dokken

platforms:
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y sudo lsb-release

  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y sudo lsb-release

  - name: debian-11
    driver:
      image: dokken/debian-11
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y sudo lsb-release

  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd

  - name: rockylinux-8
    driver:
      image: dokken/rockylinux-8
      pid_one_command: /usr/lib/systemd/systemd

  - name: amazonlinux-2
    driver:
      image: dokken/amazonlinux-2
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[cookbook-template::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      cookbook_template:
        service:
          port: 8080
          enabled: true