---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  chef_license: accept-no-persist
  product_name: chef
  product_version: 19
  install_strategy: always
  multiple_converge: 2
  enforce_idempotency: true
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-22.04
    driver:
      box: bento/ubuntu-22.04
  - name: ubuntu-20.04
    driver:
      box: bento/ubuntu-20.04
  - name: debian-11
    driver:
      box: bento/debian-11
  - name: centos-7
    driver:
      box: bento/centos-7
  - name: rockylinux-8
    driver:
      box: bento/rockylinux-8
  - name: amazonlinux-2
    driver:
      box: bento/amazonlinux-2
  - name: opensuse-leap-15
    driver:
      box: bento/opensuse-leap-15

suites:
  - name: default
    run_list:
      - recipe[cookbook-template::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      cookbook_template:
        service:
          port: 8080
          enabled: true